### ISSUE TITLE
Model weights for inference

### ISSUE THREAD

**Issue by Tianananana** [siyi-wind/MDViT#2]
Thanks for the great work! May I ask if you could release the model weights for MDViT, TransFuse, and BASE? Thank you!

**Comment by siyi-wind** [comment]
Hi, thank you for your kind words. I'm sorry that I no longer have the weights for MDViT and TransFuse. Unfortunately, I graduated from UBC and forgot to copy the weights from the server. However, I have been able to locate the weights for BASE, which you can access here[https://drive.google.com/drive/folders/1ZIav0FmGIIktf4NyxPuV5zEcuRk8Zkar?usp=sharing]. Please let me know if you encounter any issues when using them.  

Additionally, if you use the same random seed and data split as specified in the code, you should be able to replicate our results.

**Comment by Tianananana** [comment]
Ok, thank you!
